import {
  TbBrandTypescript,
  TbBrandReact,
  TbBrandNodejs,
  TbBrandVite,
  TbBrandNextjs,
  TbBrandGithub,
  TbBrandGit,
  TbBrandDocker,
  TbBrandFigma,
  TbBrandGolang,
  TbBrandCloudflare,
  TbBrandPrisma,
  TbBrandAws,
  TbBrandReactNative,
} from "react-icons/tb";
import {
  SiNestjs,
  SiClerk,
  SiTanstack,
  SiConvex,
  SiRender,
} from "react-icons/si";

export const stacks = [
  { title: "TypeScript", icon: TbBrandTypescript },
  { title: "React", icon: TbBrandReact },
  { title: "Next.js", icon: TbBrandNextjs },
  { title: "Vite", icon: TbBrandVite },
  { title: "React Native", icon: TbBrandReactNative },
  { title: "TanStack Start", icon: SiTanstack },
  { title: "Node.js", icon: TbBrandNodejs },
  { title: "NestJS", icon: SiNestjs },
  { title: "Go", icon: TbBrandGolang },
  { title: "Prisma", icon: TbBrandPrisma },
  { title: "Clerk", icon: SiClerk },
  { title: "Convex", icon: SiConvex },
  { title: "Docker", icon: TbBrandDocker },
  { title: "Cloudflare", icon: TbBrandCloudflare },
  { title: "AWS", icon: TbBrandAws },
  { title: "Render", icon: SiRender },
  { title: "Git", icon: TbBrandGit },
  { title: "GitHub", icon: TbBrandGithub },
  { title: "Figma", icon: TbBrandFigma },
];
